import{a as m,S as L,i as n}from"./assets/vendor-d93b82f1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const y=s=>`<li class="gallery-card-hw-12">
     <a class="gallery-link-hw-12" href="${s.largeImageURL}">
       <img class="gallery-img-hw-12" src="${s.webformatURL}" alt="${s.tags}" width='360' height='200'; />
       <div class="image-info-hw-12">
         <p>Likes <span>${s.likes}</span></p>
         <p>Views  <span>${s.views}</span></p>
         <p>Comments  <span>${s.comments}</span></p>
         <p>Downloads  <span>${s.downloads}</span></p>
       </div>
     </a>
   </li>`;m.defaults.baseURL="https://pixabay.com/api/";const f=(s,t)=>{const a={params:{key:"45638665-39d93a42fef97026e251908a6",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}};return m.get("",a)},u=document.querySelector(".js-form-hw-12"),l=document.querySelector(".js-gallery-hw-12"),h=document.querySelector(".js-loader-hw-12"),c=document.querySelector(".js-button-load-more-hw-12");let i=1,d="";const g=new L(".js-gallery-hw-12 a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt",overlayOpacity:1});h.classList.add("is-hidden");const w=async s=>{try{if(s.preventDefault(),d=u.elements.user_query.value.trim(),d==="")return;i=1,h.classList.remove("is-hidden"),l.innerHTML="";const t=await f(d,i);if(t.data.total===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.innerHTML="",c.classList.add("is-hidden");return}const a=t.data.hits.map(o=>y(o)).join("");l.innerHTML=a,c.classList.remove("is-hidden"),g.refresh(),Math.ceil(t.data.totalHits/15)===i&&(c.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(t){n.error({message:t.message,position:"topRight"})}finally{u.reset(),h.classList.add("is-hidden")}},v=async s=>{try{i++;const t=await f(d,i),a=t.data.hits.map(e=>y(e)).join("");l.insertAdjacentHTML("beforeend",a);const o=()=>{const{height:e}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};g.refresh(),o(),Math.ceil(t.data.totalHits/15)===i&&(c.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch{n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{h.classList.add("is-hidden")}};u.addEventListener("submit",w);c.addEventListener("click",v);
//# sourceMappingURL=commonHelpers.js.map
